// Vue/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
import { FlagProvider } from '@unleash/proxy-client-vue'

const config = {
  url: 'https://app.unleash-hosted.com/demo/api/frontend',
  clientKey: 'demo-app:dev.95ae66ab673bf467facb68b2487904f4891064d26b47e89ca498063d',
  refreshInterval: 5,
  metricsInterval: 5,
  appName: 'codesandbox-vue'
}
</script>

<template>
  <FlagProvider :config="config">
    <HelloWorld />
  </FlagProvider>
</template>

// ReactNative/App.tsx
import { FlagProvider } from "@unleash/unleash-react-native-sdk";
import FlagStatus from "./components/FlagStatus";

const config = {
  url: process.env.EXPO_PUBLIC_UNLEASH_URL,
  clientKey: process.env.EXPO_PUBLIC_UNLEASH_CLIENT_KEY,
  appName: "react-native-example",
};

export default function App() {
  return (
    <FlagProvider config={config}>
      <FlagStatus />
    </FlagProvider>
  );
}
